In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch3 = my_torch2.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch4[2] = 121
my_torch4

tensor([  0,   1, 121,   3,   4,   5,   6,   7,   8,   9])

In [7]:
my_torch4 = my_torch4.reshape(2,5)
my_torch4

tensor([[  0,   1, 121,   3,   4],
        [  5,   6,   7,   8,   9]])

In [8]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_torch5[5]

tensor(5)

In [10]:
my_torch5 = my_torch5.reshape(5,2)
my_torch5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
my_torch5[:,1]

tensor([1, 3, 5, 7, 9])

In [12]:
my_torch5[:,:1]

tensor([[0],
        [2],
        [4],
        [6],
        [8]])