In [1]:
import torch
import numpy as np

In [2]:
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([5,6,7,8])

In [3]:
tensor_1 + tensor_2

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_1,tensor_2)

tensor([ 6,  8, 10, 12])

In [5]:
tensor_1 - tensor_2

tensor([-4, -4, -4, -4])

In [6]:
torch.sub(tensor_1,tensor_2)

tensor([-4, -4, -4, -4])

In [7]:
tensor_1 / tensor_2

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [8]:
torch.div(tensor_1,tensor_2)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [9]:
tensor_1 % tensor_2

tensor([1, 2, 3, 4])

In [10]:
torch.remainder(tensor_1,tensor_2)

tensor([1, 2, 3, 4])